Add `py.typed` to officially declare typed
Otherwise, when savefigs is used as a lib and mypy invoked,
mypy will say something like:
  t.py:1: error: Skipping analyzing "savefigs": found module but no
  type hints or library stubs
  ...
  Found 1 error in 1 file (checked 1 source file)